version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network
    ports:
      - "3001:3000"

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge