version: '3'

services:    
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "npm start"
    volumes:
      - /usr/src/app/node_modules
      - ./node:/usr/src/app
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    container_name: nginx
    tty: true
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge